server:
  # 设置端口号
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /matrix

spring:
  application:
    name: matrix-basic
  # 当前项目maven激活环境，例如：dev/test/prod
  profiles:
    active: dev
#    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.liu.matrixcommon.pojo.**
  global-config:
    db-config:
      #配置逻辑删除，mybatisplus官网
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #配置日志打印，查看逻辑删除sql
  #mybatis-plus配置控制台打印完整带参数SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:9090/liu/swagger-ui.html 注意上方context-path配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# 自己的配置
file:
  local:
    # 文件上传地址
    upload-path: D:\fileNfs
matrix:
