server:
  # 设置端口号
  port: 10024
  servlet:
    # 应用的访问路径
    context-path: /liu

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matrix_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lwz.541666
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: 127.0.0.1
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.liu.common.pojo

mybatis-plus:
  global-config:
    db-config:
      #配置逻辑删除，mybatisplus官网
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #配置日志打印，查看逻辑删除sql
  #mybatis-plus配置控制台打印完整带参数SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自己的配置
matrix:
