server:
  # 设置端口号
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /matrix

spring:
  application:
    name: matrix-basic
  # 当前项目maven激活环境，例如：dev/test/prod
  profiles:
    active: dev
#    active: prod
