server:
  # 设置端口号
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /matrix

spring:
  application:
    name: matrix-basic
  threads:
    virtual:
      enabled: true
  # 当前项目maven激活环境，例如：dev/test/prod
  profiles:
    active: dev
#    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

#springdoc相关配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.matrix.admin   #按包路径匹配:一般到启动类的包名

#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文

# 自己的配置
file:
  local:
    # 文件上传地址
    upload-path: D:\fileNfs
matrix:
  # 白名单 多个用逗号分隔
  not-match: /user/tokenCode
