server:
  # 设置端口号
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /matrix

spring:
  application:
    name: matrix-basic
  # 当前项目maven激活环境，例如：dev/test/prod
  profiles:
    active: dev
#    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:9090/liu/swagger-ui.html 注意上方context-path配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# 自己的配置
file:
  local:
    # 文件上传地址
    upload-path: D:\fileNfs
matrix:
  # 白名单 多个用逗号分隔
  not-match: /user/tokenCode
