server:
  # 设置端口号
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /matrix

spring:
  application:
    name: matrix-basic
  threads:
    virtual:
      enabled: true
  # 当前项目maven激活环境，例如：dev/test/prod
  profiles:
    active: dev
#    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB

